# ============================================================
# config.py — All strategy parameters in one place
# ============================================================
# Universe updated to full Nifty 500 (300+ stocks with
# sufficient history from 2015)
# Source: NSE India / Wikipedia (as of Nov 2024)
# ============================================================

UNIVERSE = [
    # A
    "360ONE.NS", "ABB.NS", "ACC.NS", "AIAENG.NS", "APLAPOLLO.NS",
    "AUBANK.NS", "AARTIIND.NS", "ABBOTINDIA.NS", "ADANIENT.NS",
    "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIPOWER.NS",
    "ABCAPITAL.NS", "ABFRL.NS", "AEGISLOG.NS", "AJANTPHARM.NS",
    "APLLTD.NS", "ALKEM.NS", "ALKYLAMINE.NS", "ALLCARGO.NS",
    "ARE&M.NS", "AMBUJACEM.NS", "ANGELONE.NS", "APARINDS.NS",
    "APOLLOHOSP.NS", "APOLLOTYRE.NS", "ASAHIINDIA.NS",
    "ASHOKLEY.NS", "ASIANPAINT.NS", "ASTRAL.NS", "ATUL.NS",
    "AUROPHARMA.NS", "AVANTIFEED.NS", "DMART.NS", "AXISBANK.NS",

    # B
    "BEML.NS", "BSE.NS", "BAJAJ-AUTO.NS", "BAJFINANCE.NS",
    "BAJAJFINSV.NS", "BAJAJHLDNG.NS", "BALAMINES.NS",
    "BALKRISIND.NS", "BALRAMCHIN.NS", "BANDHANBNK.NS",
    "BANKBARODA.NS", "BANKINDIA.NS", "MAHABANK.NS", "BATAINDIA.NS",
    "BERGEPAINT.NS", "BDL.NS", "BEL.NS", "BHARATFORG.NS",
    "BHEL.NS", "BPCL.NS", "BHARTIARTL.NS", "BIOCON.NS",
    "BIRLACORPN.NS", "BSOFT.NS", "BLUEDART.NS", "BLUESTARCO.NS",
    "BOSCHLTD.NS", "BRIGADE.NS", "BRITANNIA.NS",

    # C
    "CESC.NS", "CGPOWER.NS", "CIEINDIA.NS", "CRISIL.NS",
    "CANFINHOME.NS", "CANBK.NS", "CAPLIPOINT.NS", "CARBORUNIV.NS",
    "CASTROLIND.NS", "CEATLTD.NS", "CENTRALBK.NS", "CDSL.NS",
    "CENTURYPLY.NS", "CHAMBLFERT.NS", "CHENNPETRO.NS",
    "CHOLAHLDNG.NS", "CHOLAFIN.NS", "CIPLA.NS", "CUB.NS",
    "COALINDIA.NS", "COFORGE.NS", "COLPAL.NS", "CAMS.NS",
    "CONCOR.NS", "COROMANDEL.NS", "CROMPTON.NS", "CUMMINSIND.NS",
    "CYIENT.NS",

    # D
    "DCMSHRIRAM.NS", "DLF.NS", "DABUR.NS", "DALBHARAT.NS",
    "DEEPAKFERT.NS", "DEEPAKNTR.NS", "DIVISLAB.NS", "DIXON.NS",
    "LALPATHLAB.NS", "DRREDDY.NS",

    # E
    "EIDPARRY.NS", "EIHOTEL.NS", "EICHERMOT.NS", "ELECON.NS",
    "ELGIEQUIP.NS", "EMAMILTD.NS", "ENDURANCE.NS", "ENGINERSIN.NS",
    "EXIDEIND.NS", "FEDERALBNK.NS", "FACT.NS", "FINEORG.NS",
    "FINCABLES.NS", "FINPIPE.NS", "FORTIS.NS",

    # G
    "GAIL.NS", "GMMPFAUDLR.NS", "GICRE.NS", "GILLETTE.NS",
    "GLAND.NS", "GLAXO.NS", "GLENMARK.NS", "GODREJCP.NS",
    "GODREJIND.NS", "GODREJPROP.NS", "GRANULES.NS", "GRASIM.NS",
    "GRSE.NS", "GRINDWELL.NS", "FLUOROCHEM.NS", "GUJGASLTD.NS",
    "GMDCLTD.NS", "GNFC.NS", "GSFC.NS", "GSPL.NS",

    # H
    "HCLTECH.NS", "HDFCAMC.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "HAVELLS.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "HAL.NS",
    "HINDCOPPER.NS", "HINDPETRO.NS", "HINDUNILVR.NS", "HINDZINC.NS",
    "HONAUT.NS", "HUDCO.NS",

    # I
    "ICICIBANK.NS", "ICICIGI.NS", "ICICIPRULI.NS", "IDFCFIRSTB.NS",
    "IEX.NS", "IGL.NS", "IRCON.NS", "IRFC.NS",
    "INDIANB.NS", "INDUSINDBK.NS", "NAUKRI.NS", "INFY.NS",
    "IOC.NS", "IPCALAB.NS", "ITC.NS",

    # J
    "JSWENERGY.NS", "JSWSTEEL.NS", "JKCEMENT.NS", "JKTYRE.NS",
    "JBCHEPHARM.NS", "JINDALSAW.NS", "JINDALSTEL.NS",
    "JSL.NS", "JUBLFOOD.NS",

    # K
    "KEI.NS", "KPIL.NS", "KAJARIACER.NS",
    "KALPATPOWR.NS", "KANSAINER.NS", "KARURVYSYA.NS",
    "KOTAKBANK.NS", "KPRMILL.NS",

    # L
    "LTTS.NS", "LTIM.NS", "LT.NS", "LICHSGFIN.NS",
    "LINDEINDIA.NS", "LUPIN.NS",

    # M
    "MRF.NS", "M&M.NS", "MFSL.NS", "MARICO.NS", "MARUTI.NS",
    "MAXHEALTH.NS", "METROPOLIS.NS", "MOTHERSON.NS", "MPHASIS.NS",
    "MRPL.NS", "MUTHOOTFIN.NS",

    # N
    "NBCC.NS", "NCC.NS", "NLCINDIA.NS", "NMDC.NS",
    "NATIONALUM.NS", "NAVINFLUOR.NS", "NESTLEIND.NS", "NTPC.NS",

    # O
    "OIL.NS", "ONGC.NS", "OFSS.NS",

    # P
    "PIIND.NS", "PNBHOUSING.NS", "PRAJIND.NS",
    "PRESTIGE.NS", "PERSISTENT.NS", "PETRONET.NS", "PIDILITIND.NS",
    "PEL.NS", "POLYCAB.NS", "POWERGRID.NS", "PFC.NS", "PNB.NS",
    "PHOENIXLTD.NS", "PVRINOX.NS",

    # R
    "RVNL.NS", "RADICO.NS", "RAILTEL.NS",
    "RAMCOCEM.NS", "RATNAMANI.NS", "RCF.NS",
    "RECLTD.NS", "RELIANCE.NS", "RITES.NS",

    # S
    "SAIL.NS", "SBICARD.NS", "SBILIFE.NS",
    "SJVN.NS", "SKFINDIA.NS", "SBIN.NS", "SCHAEFFLER.NS",
    "SHREECEM.NS", "SHRIRAMFIN.NS", "SIEMENS.NS", "SOBHA.NS",
    "SOLARINDS.NS", "SONATSOFTW.NS", "SUDARSCHEM.NS",
    "SUNDARMFIN.NS", "SUNPHARMA.NS", "SUNTV.NS", "SUPREMEIND.NS",
    "SUZLON.NS", "SYMPHONY.NS",

    # T
    "TATACOMM.NS", "TATACONSUM.NS", "TATAELXSI.NS",
    "TATAMOTORS.NS", "TATAPOWER.NS", "TATASTEEL.NS", "TCS.NS",
    "TECHM.NS", "THERMAX.NS", "TIINDIA.NS",
    "TIMKEN.NS", "TITAN.NS", "TORNTPHARM.NS", "TORNTPOWER.NS",
    "TRENT.NS", "TRIDENT.NS",

    # U
    "ULTRACEMCO.NS", "UNIONBANK.NS", "UBL.NS", "UTIAMC.NS",

    # V
    "VBL.NS", "VEDL.NS", "VINATIORGA.NS", "VOLTAS.NS",

    # W
    "WELCORP.NS", "WHIRLPOOL.NS", "WIPRO.NS",

    # Z
    "ZEEL.NS", "ZYDUSLIFE.NS",
]

BENCHMARK_TICKER = "^CRSLDX"     # Nifty 500 index (proper benchmark now)
BENCHMARK_FALLBACK = "^NSEI"     # Nifty 50 fallback if 500 unavailable

# --- Date Ranges ---
START_DATE      = "2015-01-01"
TRAIN_END_DATE  = "2018-12-31"
TEST_START_DATE = "2019-01-01"
TEST_END_DATE   = "2024-06-30"

# --- Model ---
TOP_N_STOCKS        = 20    # Match original paper
FORWARD_DAYS        = 21    # 4-week forward return
TRANSACTION_COST    = 0.0025  # 25 bps

# --- Rebalance ---
REBALANCE_FREQ = "4W-THU"

# --- Min data requirement ---
MIN_HISTORY_DATE = "2016-06-01"

# --- Paths ---
DATA_DIR   = "data"
OUTPUT_DIR = "output"
